// <auto-generated />
using System;
using ErrorMessageService.Data.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErrorMessageService.Data.Migrations
{
    [DbContext(typeof(ErrorMessageContext))]
    [Migration("20220218102346_Initial_V2")]
    partial class Initial_V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ErrorMessageService.Entities.Concrete.App", b =>
                {
                    b.Property<int>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppId"), 1L, 1);

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AppId");

                    b.ToTable("App");

                    b.HasData(
                        new
                        {
                            AppId = 1,
                            AppName = "App1"
                        },
                        new
                        {
                            AppId = 2,
                            AppName = "App2"
                        },
                        new
                        {
                            AppId = 3,
                            AppName = "App3"
                        });
                });

            modelBuilder.Entity("ErrorMessageService.Entities.Concrete.ErrorMessages", b =>
                {
                    b.Property<int>("ErrorMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ErrorMessageId"), 1L, 1);

                    b.Property<string>("Decription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<int>("SubStatusCode")
                        .HasColumnType("int");

                    b.HasKey("ErrorMessageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("ErrorMessage");

                    b.HasData(
                        new
                        {
                            ErrorMessageId = 1,
                            Decription = "This interim response indicates that the client should continue the request or ignore the response if the request is already finished.",
                            LanguageId = 1,
                            Name = "Continue",
                            StatusCode = 100,
                            SubStatusCode = 1000
                        },
                        new
                        {
                            ErrorMessageId = 2,
                            Decription = "This code is sent in response to an Upgrade request header from the client and indicates the protocol the server is switching to.",
                            LanguageId = 1,
                            Name = "Switching Protocols",
                            StatusCode = 101,
                            SubStatusCode = 1001
                        },
                        new
                        {
                            ErrorMessageId = 3,
                            Decription = "This code indicates that the server has received and is processing the request, but no response is available yet.",
                            LanguageId = 1,
                            Name = "Processing",
                            StatusCode = 102,
                            SubStatusCode = 1002
                        },
                        new
                        {
                            ErrorMessageId = 4,
                            Decription = "This status code is primarily intended to be used with the Link header, letting the user agent start preloading resources while the server prepares a response.",
                            LanguageId = 1,
                            Name = "Early Hints",
                            StatusCode = 103,
                            SubStatusCode = 1003
                        },
                        new
                        {
                            ErrorMessageId = 5,
                            Decription = "The request succeeded.",
                            LanguageId = 1,
                            Name = "Ok",
                            StatusCode = 200,
                            SubStatusCode = 2000
                        },
                        new
                        {
                            ErrorMessageId = 6,
                            Decription = "The request succeeded, and a new resource was created as a result.",
                            LanguageId = 1,
                            Name = "Created",
                            StatusCode = 201,
                            SubStatusCode = 2001
                        },
                        new
                        {
                            ErrorMessageId = 7,
                            Decription = "The request has been received but not yet acted upon.",
                            LanguageId = 1,
                            Name = "Accepted",
                            StatusCode = 202,
                            SubStatusCode = 2002
                        },
                        new
                        {
                            ErrorMessageId = 8,
                            Decription = "This response code means the returned metadata is not exactly the same as is available from the origin server, but is collected from a local or a third-party copy. ",
                            LanguageId = 1,
                            Name = "Non-Authoritative Information",
                            StatusCode = 203,
                            SubStatusCode = 2003
                        },
                        new
                        {
                            ErrorMessageId = 9,
                            Decription = "There is no content to send for this request, but the headers may be useful. ",
                            LanguageId = 1,
                            Name = "No Content",
                            StatusCode = 204,
                            SubStatusCode = 2004
                        },
                        new
                        {
                            ErrorMessageId = 10,
                            Decription = "Tells the user agent to reset the document which sent this request.",
                            LanguageId = 1,
                            Name = "Reset Content",
                            StatusCode = 205,
                            SubStatusCode = 2005
                        },
                        new
                        {
                            ErrorMessageId = 11,
                            Decription = "This response code is used when the Range header is sent from the client to request only part of a resource.",
                            LanguageId = 1,
                            Name = "Partial Content",
                            StatusCode = 206,
                            SubStatusCode = 2006
                        },
                        new
                        {
                            ErrorMessageId = 12,
                            Decription = "Conveys information about multiple resources, for situations where multiple status codes might be appropriate.",
                            LanguageId = 1,
                            Name = "Multi-Status",
                            StatusCode = 207,
                            SubStatusCode = 2007
                        },
                        new
                        {
                            ErrorMessageId = 13,
                            Decription = "The request has more than one possible response.",
                            LanguageId = 1,
                            Name = "Multiple Choice",
                            StatusCode = 300,
                            SubStatusCode = 3000
                        },
                        new
                        {
                            ErrorMessageId = 14,
                            Decription = "The URL of the requested resource has been changed permanently.",
                            LanguageId = 1,
                            Name = "Moved Permanently",
                            StatusCode = 301,
                            SubStatusCode = 3001
                        },
                        new
                        {
                            ErrorMessageId = 15,
                            Decription = "This response code means that the URI of requested resource has been changed temporarily.",
                            LanguageId = 1,
                            Name = "Found",
                            StatusCode = 302,
                            SubStatusCode = 3002
                        },
                        new
                        {
                            ErrorMessageId = 16,
                            Decription = "The server sent this response to direct the client to get the requested resource at another URI with a GET request.",
                            LanguageId = 1,
                            Name = "See Other",
                            StatusCode = 303,
                            SubStatusCode = 3003
                        },
                        new
                        {
                            ErrorMessageId = 17,
                            Decription = "This is used for caching purposes. It tells the client that the response has not been modified, so the client can continue to use the same cached version of the response.",
                            LanguageId = 1,
                            Name = "Not Modified",
                            StatusCode = 304,
                            SubStatusCode = 3004
                        },
                        new
                        {
                            ErrorMessageId = 18,
                            Decription = "Defined in a previous version of the HTTP specification to indicate that a requested response must be accessed by a proxy. ",
                            LanguageId = 1,
                            Name = "Use Proxy",
                            StatusCode = 305,
                            SubStatusCode = 3005
                        },
                        new
                        {
                            ErrorMessageId = 19,
                            Decription = "The server sends this response to direct the client to get the requested resource at another URI with same method that was used in the prior request.",
                            LanguageId = 1,
                            Name = "Temporary Redirect",
                            StatusCode = 307,
                            SubStatusCode = 3007
                        },
                        new
                        {
                            ErrorMessageId = 20,
                            Decription = "This means that the resource is now permanently located at another URI, specified by the Location: HTTP Response header. This has the same semantics as the 301 Moved Permanently HTTP response code, with the exception that the user agent must not change the HTTP method used: if a POST was used in the first request, a POST must be used in the second request.",
                            LanguageId = 1,
                            Name = "Permanent Redirect",
                            StatusCode = 308,
                            SubStatusCode = 3008
                        },
                        new
                        {
                            ErrorMessageId = 21,
                            Decription = "The server could not understand the request due to invalid syntax.",
                            LanguageId = 1,
                            Name = "Bad Request",
                            StatusCode = 400,
                            SubStatusCode = 4000
                        },
                        new
                        {
                            ErrorMessageId = 22,
                            Decription = "Although the HTTP standard specifies unauthorized, semantically this response means unauthenticated.",
                            LanguageId = 1,
                            Name = "Unauthorized",
                            StatusCode = 401,
                            SubStatusCode = 4001
                        },
                        new
                        {
                            ErrorMessageId = 23,
                            Decription = "This response code is reserved for future use. The initial aim for creating this code was using it for digital payment systems, however this status code is used very rarely and no standard convention exists.",
                            LanguageId = 1,
                            Name = "Payment Required",
                            StatusCode = 402,
                            SubStatusCode = 4002
                        },
                        new
                        {
                            ErrorMessageId = 24,
                            Decription = "The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.",
                            LanguageId = 1,
                            Name = "Forbidden",
                            StatusCode = 403,
                            SubStatusCode = 4003
                        },
                        new
                        {
                            ErrorMessageId = 25,
                            Decription = "he server can not find the requested resource. In the browser, this means the URL is not recognized. In an API, this can also mean that the endpoint is valid but the resource itself does not exist. Servers may also send this response instead of 403 Forbidden to hide the existence of a resource from an unauthorized client. This response code is probably the most well known due to its frequent occurrence on the web.",
                            LanguageId = 1,
                            Name = "Not Found",
                            StatusCode = 404,
                            SubStatusCode = 4004
                        },
                        new
                        {
                            ErrorMessageId = 26,
                            Decription = "The request method is known by the server but is not supported by the target resource. For example, an API may not allow calling DELETE to remove a resource.",
                            LanguageId = 1,
                            Name = "Method Not Allowed",
                            StatusCode = 405,
                            SubStatusCode = 4005
                        },
                        new
                        {
                            ErrorMessageId = 27,
                            Decription = "This response is sent when the web server, after performing server-driven content negotiation, doesn't find any content that conforms to the criteria given by the user agent.",
                            LanguageId = 1,
                            Name = "Not Acceptable",
                            StatusCode = 406,
                            SubStatusCode = 4006
                        },
                        new
                        {
                            ErrorMessageId = 28,
                            Decription = "This is similar to 401 Unauthorized but authentication is needed to be done by a proxy.",
                            LanguageId = 1,
                            Name = "Proxy Authentication Required",
                            StatusCode = 407,
                            SubStatusCode = 4007
                        },
                        new
                        {
                            ErrorMessageId = 29,
                            Decription = "This response is sent on an idle connection by some servers, even without any previous request by the client.",
                            LanguageId = 1,
                            Name = "Request Timeout",
                            StatusCode = 408,
                            SubStatusCode = 4008
                        },
                        new
                        {
                            ErrorMessageId = 30,
                            Decription = "This response is sent when a request conflicts with the current state of the server.",
                            LanguageId = 1,
                            Name = "Conflict",
                            StatusCode = 409,
                            SubStatusCode = 4009
                        },
                        new
                        {
                            ErrorMessageId = 31,
                            Decription = "This response is sent when the requested content has been permanently deleted from server, with no forwarding address. Clients are expected to remove their caches and links to the resource.",
                            LanguageId = 1,
                            Name = "Gone",
                            StatusCode = 410,
                            SubStatusCode = 4010
                        },
                        new
                        {
                            ErrorMessageId = 32,
                            Decription = "Server rejected the request because the Content-Length header field is not defined and the server requires it.",
                            LanguageId = 1,
                            Name = "Length Required",
                            StatusCode = 411,
                            SubStatusCode = 4011
                        },
                        new
                        {
                            ErrorMessageId = 33,
                            Decription = "The client has indicated preconditions in its headers which the server does not meet.",
                            LanguageId = 1,
                            Name = "Precondition Failed",
                            StatusCode = 412,
                            SubStatusCode = 4012
                        },
                        new
                        {
                            ErrorMessageId = 34,
                            Decription = "Request entity is larger than limits defined by server. The server might close the connection or return an Retry-After header field.",
                            LanguageId = 1,
                            Name = "Payload Too Large",
                            StatusCode = 413,
                            SubStatusCode = 4013
                        },
                        new
                        {
                            ErrorMessageId = 35,
                            Decription = "The URI requested by the client is longer than the server is willing to interpret.",
                            LanguageId = 1,
                            Name = "URI Too Long",
                            StatusCode = 414,
                            SubStatusCode = 4014
                        },
                        new
                        {
                            ErrorMessageId = 36,
                            Decription = "The range specified by the Range header field in the request cannot be fulfilled. It's possible that the range is outside the size of the target URI's data.",
                            LanguageId = 1,
                            Name = "Range Not Satisfiable",
                            StatusCode = 416,
                            SubStatusCode = 4016
                        },
                        new
                        {
                            ErrorMessageId = 37,
                            Decription = "This response code means the expectation indicated by the Expect request header field cannot be met by the server.",
                            LanguageId = 1,
                            Name = "Expectation Failed",
                            StatusCode = 417,
                            SubStatusCode = 4017
                        },
                        new
                        {
                            ErrorMessageId = 38,
                            Decription = "The server has encountered a situation it does not know how to handle.",
                            LanguageId = 1,
                            Name = "Internal Server Error",
                            StatusCode = 500,
                            SubStatusCode = 5000
                        },
                        new
                        {
                            ErrorMessageId = 39,
                            Decription = "The request method is not supported by the server and cannot be handled. The only methods that servers are required to support (and therefore that must not return this code) are GET and HEAD.",
                            LanguageId = 1,
                            Name = "Not Implemented",
                            StatusCode = 501,
                            SubStatusCode = 5001
                        },
                        new
                        {
                            ErrorMessageId = 40,
                            Decription = "This error response means that the server, while working as a gateway to get a response needed to handle the request, got an invalid response.",
                            LanguageId = 1,
                            Name = "Bad Gateway",
                            StatusCode = 502,
                            SubStatusCode = 5002
                        },
                        new
                        {
                            ErrorMessageId = 41,
                            Decription = "The server is not ready to handle the request. Common causes are a server that is down for maintenance or that is overloaded. Note that together with this response, a user-friendly page explaining the problem should be sent. This response should be used for temporary conditions and the Retry-After HTTP header should, if possible, contain the estimated time before the recovery of the service. The webmaster must also take care about the caching-related headers that are sent along with this response, as these temporary condition responses should usually not be cached.",
                            LanguageId = 1,
                            Name = "Service Unavailable",
                            StatusCode = 503,
                            SubStatusCode = 5003
                        },
                        new
                        {
                            ErrorMessageId = 42,
                            Decription = "This error response is given when the server is acting as a gateway and cannot get a response in time.",
                            LanguageId = 1,
                            Name = "Gateway Timeout",
                            StatusCode = 504,
                            SubStatusCode = 5004
                        },
                        new
                        {
                            ErrorMessageId = 43,
                            Decription = "Şimdiye kadar her şeyin yolunda gittiğinin ve isteğin henüz sunucu tarafından reddedilmediğinin bir göstergesidir.",
                            LanguageId = 2,
                            Name = "Devam",
                            StatusCode = 100,
                            SubStatusCode = 1000
                        },
                        new
                        {
                            ErrorMessageId = 44,
                            Decription = "Bu aşamada, sunucunun bir istemci tarafından talep edildiği gibi protokolü değiştirdiğini belirtir. Sunucu daha sonra protokolün değiştirildiğini belirtmek için yanıt başlığında bir yükseltme yapar.",
                            LanguageId = 2,
                            Name = "Anahtarlama Protokolü",
                            StatusCode = 101,
                            SubStatusCode = 1001
                        },
                        new
                        {
                            ErrorMessageId = 45,
                            Decription = "Bu HTTP durum kodu , sunucunun isteği aldığını ve işlediğini, ancak henüz bir yanıt olmadığını gösterir. ",
                            LanguageId = 2,
                            Name = "İşlem",
                            StatusCode = 102,
                            SubStatusCode = 1002
                        },
                        new
                        {
                            ErrorMessageId = 46,
                            Decription = "Bu HTTP durum kodu, esas olarak, sunucu bir HTTP mesajı göndermeden önce bazı yanıt başlıklarını döndürmek için kullanılır. ",
                            LanguageId = 2,
                            Name = "Erken İpuçları",
                            StatusCode = 103,
                            SubStatusCode = 1003
                        },
                        new
                        {
                            ErrorMessageId = 47,
                            Decription = "HTTP 200 durum kodu, yanıtın başarılı olduğunu gösterir. Yani, istemci ile sunucu arasındaki iletişim herhangi bir hata olmadan sorunsuz bir şekilde yürütülmüştür.",
                            LanguageId = 2,
                            Name = "Tamam",
                            StatusCode = 200,
                            SubStatusCode = 2000
                        },
                        new
                        {
                            ErrorMessageId = 48,
                            Decription = "Bu, talebin sadece başarılı olmadığını, aynı zamanda bir kaynağın da yaratıldığını gösterir. Bu durum kodu, sunucuya gönderilen kaynağı tanımladığı için genellikle bir POST isteğiyle birlikte gelir.",
                            LanguageId = 2,
                            Name = "Oluşturuldu",
                            StatusCode = 201,
                            SubStatusCode = 2001
                        },
                        new
                        {
                            ErrorMessageId = 49,
                            Decription = "Bu, bir istemcinin sunucuda bir şey yaratma talebinde bulunduğu, ardından yapılan talebin kabul edildiği, ancak hala bir miktar işlemden geçtiği için henüz tamamlanmadığı anlamına gelir.",
                            LanguageId = 2,
                            Name = "Onaylandı",
                            StatusCode = 202,
                            SubStatusCode = 2002
                        },
                        new
                        {
                            ErrorMessageId = 50,
                            Decription = "Bu, başarılı bir isteği gösterir, ancak varlık başlığı, kaynak sunucununkinden değiştirilmiştir. Vekilin bir değişiklik uygulandığında konut sakinlerine bir uyarı göndermesine izin verir.",
                            LanguageId = 2,
                            Name = "Yetersiz Bilgi",
                            StatusCode = 203,
                            SubStatusCode = 2003
                        },
                        new
                        {
                            ErrorMessageId = 51,
                            Decription = "Bu, gönderilen isteğin alındığı, ancak yanıt yükünde gönderilecek ek veri olmadığı anlamına gelir. PUT yöntemi çoğunlukla 204 yanıtı için kullanılır ve varsayılan olarak önbelleğe alınabilir.",
                            LanguageId = 2,
                            Name = "İçerik Yok",
                            StatusCode = 204,
                            SubStatusCode = 2004
                        },
                        new
                        {
                            ErrorMessageId = 52,
                            Decription = "Burada istek başarılı bir şekilde işlenir, ancak yanıt kullanıcıya belge görünümünü sıfırlamasını söyler, böylece istek sunucudan alındığı orijinal durumuna geri döner.",
                            LanguageId = 2,
                            Name = "İçeriği Baştan al",
                            StatusCode = 205,
                            SubStatusCode = 2005
                        },
                        new
                        {
                            ErrorMessageId = 53,
                            Decription = "GET için kısmi içerik (içeriğin bir belirli bir parçası) başarılıyla döndürülmüştür.",
                            LanguageId = 2,
                            Name = "Kısmi İçerik",
                            StatusCode = 206,
                            SubStatusCode = 2006
                        },
                        new
                        {
                            ErrorMessageId = 54,
                            Decription = "Sunucu, mesajın gövdesine XML belgesi olarak yerleştirilmiş olan birçok bağımsız işlemin sonucunu bir kerede geçti.",
                            LanguageId = 2,
                            Name = "Çok-Statü",
                            StatusCode = 207,
                            SubStatusCode = 2007
                        },
                        new
                        {
                            ErrorMessageId = 55,
                            Decription = "Bu HTTP kodu, bir kullanıcının seçebileceği çok sayıda seçeneği veya kaynağı gösterir ve her bir seçenek veya kaynak benzersiz bir şekilde tanımlanabilir.Belirli bir yanıtı seçmenin genel olarak kabul edilmiş bir yolu olmadığından, bu yanıt kodu nadiren kullanılır.",
                            LanguageId = 2,
                            Name = "Çok Seçenek",
                            StatusCode = 300,
                            SubStatusCode = 3000
                        },
                        new
                        {
                            ErrorMessageId = 56,
                            Decription = "Burada, kaynağa yapılacak tüm gelecekteki istekler belirli bir URL'ye yönlendirilmelidir. Artık var olmayan bir sayfadan yönlendirme yapmak için kullanılabilir.",
                            LanguageId = 2,
                            Name = "Kalıcı Taşındı",
                            StatusCode = 301,
                            SubStatusCode = 3001
                        },
                        new
                        {
                            ErrorMessageId = 57,
                            Decription = "Bu yanıt, 301 HTTP durum koduna benzer. Buradaki fark, istenen kaynağın geçici olarak belirli bir başlığa taşınmış olmasıdır.",
                            LanguageId = 2,
                            Name = "Geçici Taşındı",
                            StatusCode = 302,
                            SubStatusCode = 3002
                        },
                        new
                        {
                            ErrorMessageId = 58,
                            Decription = "Bu HTTP durum kodu, bu isteğin yanıtının başka bir URL'e yönlendirildiğini gösterir. Bu durum kodu, herhangi bir HTTP yöntemi için geçerlidir.",
                            LanguageId = 2,
                            Name = "Diğerlerine Bak",
                            StatusCode = 303,
                            SubStatusCode = 3003
                        },
                        new
                        {
                            ErrorMessageId = 59,
                            Decription = "Burada, kullanıcı aracısı son kaynağın önbelleğe alınmış bir kopyasına sahip olduğundan, istenen kaynağı yeniden göndermeye gerek yoktur. Amaç, kullanıcı aracısının en son güncellemenin bir kopyasına zaten sahip olması nedeniyle veri aktarımını en aza indirmektir.",
                            LanguageId = 2,
                            Name = "Güncellenmedi",
                            StatusCode = 304,
                            SubStatusCode = 3004
                        },
                        new
                        {
                            ErrorMessageId = 60,
                            Decription = "Sunucu tarafından döndürülen proxy'in kullanılması gerektiği belirtilir.",
                            LanguageId = 2,
                            Name = "Proxy Kullan",
                            StatusCode = 305,
                            SubStatusCode = 3005
                        },
                        new
                        {
                            ErrorMessageId = 61,
                            Decription = "Bu durumda, yanıt kodu, istenen kaynağın geçici olarak başka bir URL'e taşındığını gösterir. İstemcinin bir istekte bulunmak için orijinal URL'i kullanmaya devam etmesi beklenir.",
                            LanguageId = 2,
                            Name = "Geçici olarak yeniden gönder",
                            StatusCode = 307,
                            SubStatusCode = 3007
                        },
                        new
                        {
                            ErrorMessageId = 62,
                            Decription = "Bu durumda, istenen kaynağa, isteklerin sorunsuz çalışmasına izin veren yeni bir kalıcı URL atanmıştır. Değiştirilebilen 301 HTTP durum kodunun aksine, yeniden yönlendirme sırasında istek yöntemi değişmez.",
                            LanguageId = 2,
                            Name = "Kalıcı Yönlendirme",
                            StatusCode = 308,
                            SubStatusCode = 3008
                        },
                        new
                        {
                            ErrorMessageId = 63,
                            Decription = "Bu, alınan isteğin yanlış söz diziminden kaynaklanabilecek bir hata nedeniyle sunucu tarafından işlenemediğini gösterir. Sunucu, bir sonraki talep alındığında bazı değişikliklerin yapılmasını bekler, aksi takdirde aynı hata devam eder.",
                            LanguageId = 2,
                            Name = "Kötü İstek",
                            StatusCode = 400,
                            SubStatusCode = 4000
                        },
                        new
                        {
                            ErrorMessageId = 64,
                            Decription = "Bu durumda, alınan bir yanıta erişim sağlamak için yetkilendirme gerekir. Bu HTTP durum kodu HTTP 403'e benzer. Ancak burada, talebin kabul edilebilmesi için geçerli kimlik bilgilerine sahip olması beklenir.",
                            LanguageId = 2,
                            Name = "Yetkisiz",
                            StatusCode = 401,
                            SubStatusCode = 4001
                        },
                        new
                        {
                            ErrorMessageId = 65,
                            Decription = "Ödeme gerekiyor. (gelecekte kullanılması için ayrılmıştır).",
                            LanguageId = 2,
                            Name = "Ödeme Gerekli",
                            StatusCode = 402,
                            SubStatusCode = 4002
                        },
                        new
                        {
                            ErrorMessageId = 66,
                            Decription = "Bu HTTP durum kodu, kullanıcı-istemcinin geçerli bir veriye sahip olduğu ancak sunucu tarafından erişimin reddedildiği anlamına gelir. Kullanıcının söz konusu kaynak üzerinde herhangi bir hakka sahip olmasına izin verilmediğinden, tekrarlanan girişimlerde bulunmak kullanıcı olarak başarılı bir yanıt vermeyecektir.",
                            LanguageId = 2,
                            Name = "Yasaklandı",
                            StatusCode = 403,
                            SubStatusCode = 4003
                        },
                        new
                        {
                            ErrorMessageId = 67,
                            Decription = "Bu HTTP kodu, istenen kaynağın sunucu tarafından bulunamayacağı anlamına gelir. Bu, geçici bir aksaklıktan kaynaklanıyor olabilir ve gelecekte başka bir istekte bulunulursa kaynak kullanılabilir olabilir. Çoğunlukla, 404'e götüren bağlantılara genellikle bozuk bağlantılar denir.",
                            LanguageId = 2,
                            Name = "Sayfa Bulunamadı",
                            StatusCode = 404,
                            SubStatusCode = 4004
                        },
                        new
                        {
                            ErrorMessageId = 68,
                            Decription = "Bu HTTP kodu, istenen bir yöntemin, sunucu tarafından tanındığında bile istenen kaynak için desteklenmediği anlamına gelir. Kaynak bir GET veya POST yöntemi bekliyor olabilir, ancak bir DELETE veya PUT yöntemi alırsa, yapılan istek 405 olarak reddedilecektir.",
                            LanguageId = 2,
                            Name = "İzin verilmeyen Metod",
                            StatusCode = 405,
                            SubStatusCode = 4005
                        },
                        new
                        {
                            ErrorMessageId = 69,
                            Decription = "İstemcinin Accept header'ında verilen özellik karşılanamıyor.",
                            LanguageId = 2,
                            Name = "Kabul Edilemez",
                            StatusCode = 406,
                            SubStatusCode = 4006
                        },
                        new
                        {
                            ErrorMessageId = 70,
                            Decription = "Proxy üzerinden yetkilendirme gerekir.",
                            LanguageId = 2,
                            Name = "Proxy Kimlik Doğrulaması Gerekli",
                            StatusCode = 407,
                            SubStatusCode = 4007
                        },
                        new
                        {
                            ErrorMessageId = 71,
                            Decription = "İstek zaman aşımına uğradı (belirli bir sürede istek tamamlanamadı).",
                            LanguageId = 2,
                            Name = "İstek zaman aşımına uğradı",
                            StatusCode = 408,
                            SubStatusCode = 4008
                        },
                        new
                        {
                            ErrorMessageId = 72,
                            Decription = "İstek içinde çelişki var.",
                            LanguageId = 2,
                            Name = "Fikir ayrılığı",
                            StatusCode = 409,
                            SubStatusCode = 4009
                        },
                        new
                        {
                            ErrorMessageId = 73,
                            Decription = "Kaynak artık yok.",
                            LanguageId = 2,
                            Name = "Gitmiş",
                            StatusCode = 410,
                            SubStatusCode = 4010
                        },
                        new
                        {
                            ErrorMessageId = 74,
                            Decription = "İstekte Content - Length (içeriğin boyutu) belirtilmemiş.",
                            LanguageId = 2,
                            Name = "Gerekli Uzunluk",
                            StatusCode = 411,
                            SubStatusCode = 4011
                        },
                        new
                        {
                            ErrorMessageId = 75,
                            Decription = "Sunucu istekte belirtilen bazı önkoşulları karşılamıyor.",
                            LanguageId = 2,
                            Name = "Ön Koşul Başarısız",
                            StatusCode = 412,
                            SubStatusCode = 4012
                        },
                        new
                        {
                            ErrorMessageId = 76,
                            Decription = "İsteğin boyutu çok büyük olduğu için işlenemedi.",
                            LanguageId = 2,
                            Name = "Yük Çok Büyük",
                            StatusCode = 413,
                            SubStatusCode = 4013
                        },
                        new
                        {
                            ErrorMessageId = 77,
                            Decription = "URI (URL) fazla büyük.",
                            LanguageId = 2,
                            Name = "URI Çok Uzun",
                            StatusCode = 414,
                            SubStatusCode = 4014
                        },
                        new
                        {
                            ErrorMessageId = 78,
                            Decription = "İstenilen kaynak istenilen medya tipini desteklemiyor.",
                            LanguageId = 2,
                            Name = "Menzil Tatmin Edilemez",
                            StatusCode = 416,
                            SubStatusCode = 4016
                        },
                        new
                        {
                            ErrorMessageId = 79,
                            Decription = "İstek yapılan parça (bir dosyanın bir parçası vb..) sunucu tarafından verilebiliyor veya uygun değil.",
                            LanguageId = 2,
                            Name = "Beklenti Başarısız",
                            StatusCode = 417,
                            SubStatusCode = 4017
                        },
                        new
                        {
                            ErrorMessageId = 80,
                            Decription = "Burada, belirli bir isteğin, isteği tamamlayamamasına neden olan beklenmedik bir durumla karşılaştığı anlamına gelir. Kullanıcının bu HTTP durum kodunu web sayfasında görmesi beklenmez.",
                            LanguageId = 2,
                            Name = "İç Sunucu Hatası",
                            StatusCode = 500,
                            SubStatusCode = 5000
                        },
                        new
                        {
                            ErrorMessageId = 81,
                            Decription = "Bu HTTP durum kodu, sunucunun belirli bir isteği tamamlamak için gereken gereksinimleri desteklemediğini veya sahip olmadığını gösterir. Bu, kullanıcı-istemcinin erişmeye çalıştığı sunucunun düzeltilmesi gerektiği anlamına gelir.",
                            LanguageId = 2,
                            Name = "Uygulanmadı",
                            StatusCode = 501,
                            SubStatusCode = 5001
                        },
                        new
                        {
                            ErrorMessageId = 82,
                            Decription = "Bu HTTP kodu, sunucunun proxy olarak hareket ederken istekte bulunurken sunucudan geçersiz bir yanıt aldığını gösterir.",
                            LanguageId = 2,
                            Name = "Kötü Ağ Geçidi",
                            StatusCode = 502,
                            SubStatusCode = 5002
                        },
                        new
                        {
                            ErrorMessageId = 83,
                            Decription = "Bu HTTP durum kodu, geçici bir durumu gösterir. Bu, sunucuya yapılan isteğin şu anda eylemi gerçekleştiremediği anlamına gelir; bu, bakım nedeniyle veya sunucunun aşırı yüklenmiş olduğu anlamına gelebilir.",
                            LanguageId = 2,
                            Name = "Hizmet kullanılamıyor",
                            StatusCode = 503,
                            SubStatusCode = 5003
                        },
                        new
                        {
                            ErrorMessageId = 84,
                            Decription = "Bu HTTP durum kodu, sunucunun bir proxy gibi davrandığını, isteği beklenen zaman aralığında göndermediğini gösterir. Bu düzeltmenin sunucudan gelmesi bekleniyor.",
                            LanguageId = 2,
                            Name = "Ağ Geçidi Zaman Aşımı",
                            StatusCode = 504,
                            SubStatusCode = 5004
                        });
                });

            modelBuilder.Entity("ErrorMessageService.Entities.Concrete.ErrorsDetails", b =>
                {
                    b.Property<int>("ErrorsDetailsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ErrorsDetailsId"), 1L, 1);

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<int>("ErrorMessageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ErrorsDetailsId");

                    b.HasIndex("AppId");

                    b.HasIndex("ErrorMessageId");

                    b.ToTable("ErrorsDetails");
                });

            modelBuilder.Entity("ErrorMessageService.Entities.Concrete.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageId"), 1L, 1);

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguagePath")
                        .HasColumnType("int");

                    b.HasKey("LanguageId");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            LanguageName = "İngilizce",
                            LanguagePath = 1
                        },
                        new
                        {
                            LanguageId = 2,
                            LanguageName = "Türkçe",
                            LanguagePath = 2
                        });
                });

            modelBuilder.Entity("ErrorMessageService.Entities.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ErrorMessageService.Entities.Concrete.ErrorMessages", b =>
                {
                    b.HasOne("ErrorMessageService.Entities.Concrete.Language", null)
                        .WithMany("ErrorMessages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ErrorMessageService.Entities.Concrete.ErrorsDetails", b =>
                {
                    b.HasOne("ErrorMessageService.Entities.Concrete.App", "App")
                        .WithMany("ErrorsDetails")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ErrorMessageService.Entities.Concrete.ErrorMessages", "ErrorMessage")
                        .WithMany("ErrorDetails")
                        .HasForeignKey("ErrorMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("ErrorMessage");
                });

            modelBuilder.Entity("ErrorMessageService.Entities.Concrete.App", b =>
                {
                    b.Navigation("ErrorsDetails");
                });

            modelBuilder.Entity("ErrorMessageService.Entities.Concrete.ErrorMessages", b =>
                {
                    b.Navigation("ErrorDetails");
                });

            modelBuilder.Entity("ErrorMessageService.Entities.Concrete.Language", b =>
                {
                    b.Navigation("ErrorMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
